# Generated by Django 5.1.3 on 2024-11-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_farmer_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedFarmer',
            fields=[
            ],
            options={
                'verbose_name': 'Approved Farmer',
                'verbose_name_plural': 'Approved Farmers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.farmer',),
        ),
        migrations.CreateModel(
            name='PendingFarmer',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Farmer',
                'verbose_name_plural': 'Pending Farmers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.farmer',),
        ),
        migrations.CreateModel(
            name='RejectedFarmer',
            fields=[
            ],
            options={
                'verbose_name': 'Rejected Farmer',
                'verbose_name_plural': 'Rejected Farmers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.farmer',),
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
