# Generated by Django 5.1.3 on 2024-11-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_approvedfarmer_pendingfarmer_rejectedfarmer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
