# Generated by Django 4.2 on 2024-11-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="farm_location",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="farmer",
            name="farm_size",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
