# Generated by Django 4.2 on 2024-11-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_farmer_farm_location_farmer_farm_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="farm_location",
            field=models.CharField(default="not specified", max_length=255),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="farm_size",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
