# Generated by Django 4.2 on 2024-11-30 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_farmer_farm_location_farmer_farm_size"),
        ("products", "0005_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="farm",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="farm",
        ),
        migrations.AddField(
            model_name="product",
            name="farmer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.farmer",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name="Farm",
        ),
        migrations.DeleteModel(
            name="Inventory",
        ),
    ]
