# Generated by Django 4.2 on 2024-11-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="farm_location",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="farmer",
            name="farm_size",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
