# Generated by Django 5.1.2 on 2024-11-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="farmer",
            name="farm_location",
            field=models.CharField(
                blank=True, default="Unknown farm location", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
