# Generated by Django 5.1.2 on 2024-11-05 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_buyer_payment_method_farmer_farm_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="farm_location",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="verified",
        ),
    ]
