# Generated by Django 5.1.2 on 2024-11-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_buyer_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
