# Generated by Django 5.1.2 on 2024-11-10 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.buyer"
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "admin"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.cart"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.farmer"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.farm"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.farm"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
    ]
