# Generated by Django 5.1.2 on 2024-11-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_category_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="Vegetables", max_length=100, unique=True),
        ),
    ]
