# Generated by Django 5.1.3 on 2024-11-19 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_name'),
        ('users', '0003_approvedfarmer_pendingfarmer_rejectedfarmer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.farmer'),
        ),
    ]
