# Generated by Django 5.1.3 on 2024-11-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_farm_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
