# Generated by Django 5.1.3 on 2024-11-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_image_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
